name: Check WoW Prices

on:
  schedule:
    - cron: "*/5 * * * *" # Каждые 5 минут UTC

jobs:
  check-prices:
    runs-on: ubuntu-latest
    timeout-minutes: 2 # 2 минуты на выполнение
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Run price check
        run: node src/main.js
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
